version: "3.8"

services:
  node:
    build: .
    container_name: node
    environment:
      - RPC=${RPC}
      - BLOCK=24210014
      - CHAIN_ID=8453
    ports:
      - "8545:8545"
    volumes:
      - "./cache:/hardhat/cache"